### ISSUE TITLE
google.api_core.exceptions.ResourceExhausted: 429 Received message larger than max

### ISSUE THREAD

**Issue by reallyasi9** [googleapis/python-automl#120] opened 2021-01-07 16:30 UTC
When running the example code listed on the [Google AutoML Tables documentation](https://cloud.google.com/automl-tables/docs/explain#getting_model_feature_importance) for several recently-trained AutoML Tables models, I am receiving a `google.api_core_exceptions.ResourceExhausted` exception. This is a new development--the example code included below worked in late December 2020 with exactly the same software, exactly the same installed library versions, and exactly the same AutoML Tables models.

#### Environment details

  - OS type and version: Both Windows 10 (local machine) and Linux (Ubuntu 20.10 on GCP VM)
  - Python version: `Python 3.8.7`
  - pip version: `pip 20.3.1`
  - `google-cloud-automl` version: `Version: 2.1.0`

#### Steps to reproduce

  1. Wait until 2021.
  2. Run the example code for "Getting Model Feature Importance" on the Google AutoML Tables documentation [here](https://cloud.google.com/automl-tables/docs/explain#getting_model_feature_importance) for a trained AutoML Tables model.

#### Code example

```python
from google.cloud import automl_v1beta1 as automl

project_id = "my-project-id"
compute_region = "my.compute.region"
model_display_name = "my_automl_tables_model"

client = automl.TablesClient(project=project_id, region=compute_region)
client.get_model(model_display_name=model_display_name)
```

#### Stack trace
```
Traceback (most recent call last):
  File "C:\xxx\.virtualenvs\xxx\lib\site-packages\google\api_core\grpc_helpers.py", line 57, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "C:\xxx\.virtualenvs\xxx\lib\site-packages\grpc\_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "C:\xxx\.virtualenvs\xxx\lib\site-packages\grpc\_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.RESOURCE_EXHAUSTED
        details = "Received message larger than max (7011783 vs. 4194304)"
        debug_error_string = "{"created":"@1610034456.335000000","description":"Received message larger than max (7011783 vs. 4194304)","file":"src/core/ext/filters/message_size/message_size_filter.cc","file_line":208,"grpc_status":8}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    model = client.get_model(model_display_name=model_display_name)
  File "C:\xxx\.virtualenvs\xxx\lib\site-packages\google\cloud\automl_v1beta1\services\tables\tables_client.py", line 2588, in get_model
    self.list_models(project=project, region=region),
  File "C:\xxx\.virtualenvs\xxx\lib\site-packages\google\cloud\automl_v1beta1\services\tables\tables_client.py", line 2143, in list_models
    return self.auto_ml_client.list_models(request=request, **method_kwargs)
  File "C:\xxx\.virtualenvs\xxx\lib\site-packages\google\cloud\automl_v1beta1\services\auto_ml\client.py", line 1799, in list_models
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "C:\xxx\.virtualenvs\xxx\lib\site-packages\google\api_core\gapic_v1\method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "C:\xxx\.virtualenvs\xxx\lib\site-packages\google\api_core\retry.py", line 281, in retry_wrapped_func
    return retry_target(
  File "C:\xxx\.virtualenvs\xxx\lib\site-packages\google\api_core\retry.py", line 184, in retry_target
    return target()
  File "C:\xxx\.virtualenvs\xxx\lib\site-packages\google\api_core\grpc_helpers.py", line 59, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.ResourceExhausted: 429 Received message larger than max (7011783 vs. 4194304)
```

Thank you for your help.

**Comment by munkhuushmgl** [comment] 2021-01-08 21:27
I was not able to repro this issue 
I ran 20 times still getting no error
![image](https://user-images.githubusercontent.com/45373284/104065723-1baa2d00-51b5-11eb-875c-fd6facd628da.png)


Code snippet i used:

```
project_id = "project_id"
compute_region = "us-central1"
model_display_name = "mode_display_name"


from google.cloud import automl_v1beta1 as automl

client = automl.TablesClient(project=project_id, region=compute_region)

# Get complete detail of the model.
model = client.get_model(model_display_name=model_display_name)

# Retrieve deployment state.
if model.deployment_state == automl.Model.DeploymentState.DEPLOYED:
    deployment_state = "deployed"
else:
    deployment_state = "undeployed"

# get features of top importance
feat_list = [
    (column.feature_importance, column.column_display_name)
    for column in model.tables_model_metadata.tables_model_column_info
]
feat_list.sort(reverse=True)
if len(feat_list) < 10:
    feat_to_show = len(feat_list)
else:
    feat_to_show = 10

# Display the model information.
print("Model name: {}".format(model.name))
print("Model id: {}".format(model.name.split("/")[-1]))
print("Model display name: {}".format(model.display_name))
print("Features of top importance:")
for feat in feat_list[:feat_to_show]:
    print(feat)
print("Model create time: {}".format(model.create_time))
print("Model deployment state: {}".format(deployment_state))
```

**Comment by reallyasi9** [comment] 2021-01-12 15:33
The following work-around mitigates the issue:

```python
from google.cloud.automl_v1beta1 import AutoMlClient, TablesClient
from google.cloud.automl_v1beta1.services.auto_ml.transports.grpc import AutoMlGrpcTransport

# Resizing the 'grpc.max_receive_message_length' for AutoMlClient
automl_channel = AutoMlGrpcTransport.create_channel(
    options=[("grpc.max_receive_message_length", 10 * 1024 * 1024)])  # 10 MB, or whatever size is needed
automl_transport = AutoMlGrpcTransport(channel=automl_channel)
automl_client = AutoMlClient(transport=automl_transport)

project_id = "my-project-id"
region = "us-central1"
model_display_name = "my-model-display-name"
client = TablesClient(project=project_id, region=region, client=automl_client)

client.get_model(model_display_name=model_display_name)
```

If this is what is necessary to access larger models from the python API, should this be added to the documentation?

**Comment by kweinmeister** [comment] 2021-11-10 14:12
Hi @reallyasi9, thanks for the helpful suggestion for the documentation. Since we weren't able to reproduce it on our end, it would be great if you can verify if you're still seeing this behavior with the latest library version. Then, we can determine if it was a transient issue, or something that should permanently belong in the docs. Thank you!

**Comment by orionnye** [comment] 2021-11-29 18:15
I've been unable to reproduce this, so I'm going to close the issue.

**Closed by orionnye** 2021-11-29 18:15 UTC
Labels: status: investigating, type: docs, api: automl
