### ISSUE TITLE
AutoML Tables `display_evaluation` function doesn't work properly in regression case

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-automl#15] opened 2020-02-25 00:39 UTC
@amygdala @sirtorry 

Copied from https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2598, since issues can't be transferred across GitHub organizations.

---

the automl tables `display_evaluation` function here: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/tables/automl/automl_tables_model.py#L244
does not work properly in at least the regression case, where it's grabbing the first eval in the list, when it should be using the second element.

**Comment by aribray** [comment] 2021-07-07 19:01
@busunkim96  According to [this comment](https://github.com/googleapis/python-automl/blob/79b80f2ed3a7661407a11de346cd6d49ed5b4bdf/google/cloud/automl_v1beta1/services/tables/tables_client.py#L2202) in `tables_client.py`, there will only be one evaluation returned for a regression model.

I looked at the provided documentation, but this comment seems to be the only place where this is mentioned.

`display_evaluation` for a classification model is working.

**Comment by busunkim96** [comment] 2021-07-08 16:47
Hmm I don't think I have enough context to understand what the expected behavior is.  @helinwang is the original author of `tables_client.py` and might be able to help clarify.

**Comment by matthewayne** [comment] 2021-11-08 01:01
@amygdala can you provide some sample code reproducing the error with the output and output your expect?

**Comment by matthewayne** [comment] 2022-07-14 16:23
Closing for now, please reopen or create a new issue with the requested context if you're still having this issue

**Closed by matthewayne** 2022-07-14 16:23 UTC
Labels: type: feature request, api: automl, priority: p3
