### ISSUE TITLE
BatchPredict could not start due to empty input CSV file.

### ISSUE THREAD

**Issue by tc64** [googleapis/python-automl#21] opened 2020-03-18 12:57 UTC
#### Environment details

1. AutoML Natural Language batch predict (google.cloud.automl_v1.gapic.prediction_service_client.PredictionServiceClient.batch_predict)
2. Ubuntu 16.04
3. 3.7.5
4. 
google-api-core==1.16.0
google-auth==1.11.0
google-cloud-automl==0.10.0
google-cloud-core==1.3.0
google-cloud-storage==1.26.0
google-resumable-media==0.5.0
googleapis-common-protos==1.51.0

#### Steps to reproduce

  1. basically this: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/automl/cloud-client/batch_predict.py

#### Code example

```python
logging.info("Make batch prediction")
    
    # Get the full path of the model.
    model_full_id = prediction_client.model_path(
        project, location, model_id
    )
    
    gcs_source = automl.types.GcsSource(input_uris=[input_path])

    input_config = automl.types.BatchPredictInputConfig(gcs_source=gcs_source)
    gcs_destination = automl.types.GcsDestination(output_uri_prefix=output_path)
    output_config = automl.types.BatchPredictOutputConfig(
        gcs_destination=gcs_destination
    )

    response = prediction_client.batch_predict(
        model_full_id, input_config, output_config
    )
    
    params = {"model_id":model_id,
             "model_full_id":model_full_id,
             "gcs_source":gcs_source,
             "input_config":input_config,
             "gcs_destination":gcs_destination,
             "output_config":output_config,
             "input_path":input_path,
             "output_path":output_path}
    
    logging.debug(params)

    logging.debug("Waiting for operation to complete...")
    logging.info("Batch Prediction results saved to Cloud Storage bucket. {}".format(response.result()))
```
Above, `prediction_client` is a `google.cloud.automl_v1.PredictionServiceClient`

#### Stack trace
```
DEBUG:root:Waiting for operation to complete...
DEBUG:google.api_core.retry:Retrying due to , sleeping 0.9s ...
Traceback (most recent call last):
  File "/home/tc/ml_experiments_plus1/call_segmentation/batch_predict.py", line 113, in <module>
    batch_predict(prediction_client, project_id, compute_region, model_id, input_path, output_path)
  File "/home/tc/ml_experiments_plus1/call_segmentation/batch_predict.py", line 41, in batch_predict
    logging.info("Batch Prediction results saved to Cloud Storage bucket. {}".format(response.result()))
  File "/home/tc/anaconda3_7/envs/ml_experiments_plus1/lib/python3.7/site-packages/google/api_core/future/polling.py", line 127, in result
    raise self._exception
google.api_core.exceptions.GoogleAPICallError: None BatchPredict could not start due to empty input CSV file.
```
The CSV file is not empty, I've tried with a few. The bucket is in us central 1. 

Thanks!

**Comment by hensilva** [comment] 2020-03-23 12:15
I'm having the same issue. As a workaround I used a single JSONL file with several lines instead of a CSV pointing to several JSONL files. The only downside is that the output is a single JSONL instead of multiple files.

**Comment by tc64** [comment] 2020-03-29 14:35
Thanks @hensilva, will check if this applies to our situation and reply.

**Comment by lousenwei** [comment] 2020-03-30 07:57
I have the same issue for text classification which doesn't accept JSONL. I checked the document, it seems receive csv with direct mutli-lines content but it seems not.
csv file has all txt files while each txt file can only have one content inside, it is very inefficient.

**Comment by munkhuushmgl** [comment] 2020-04-30 22:21
@tc64 Could you provide more info about .csv file and what does look like inside of csv file?

**Comment by aaronbriel** [comment] 2020-05-05 01:32
I'm seeing the same issue. Attempting to use a JSONL file fails with `The file extension `jsonl` is not supported.` Using a simple csv with a single column containing multiple rows of text fails with `google.api_core.exceptions.GoogleAPICallError: None BatchPredict could not start due to empty input CSV file.`.

**Comment by aaronbriel** [comment] 2020-05-05 01:57
> I'm having the same issue. As a workaround I used a single JSONL file with several lines instead of a CSV pointing to several JSONL files. The only downside is that the output is a single JSONL instead of multiple files (NLP Text Extraction in my scenario. Not all accept JSON input)

How did you get around the supported file extension restriction?

**Comment by hensilva** [comment] 2020-05-05 13:58
> > I'm having the same issue. As a workaround I used a single JSONL file with several lines instead of a CSV pointing to several JSONL files. The only downside is that the output is a single JSONL instead of multiple files (NLP Text Extraction in my scenario. Not all accept JSON input)
> 
> How did you get around the supported file extension restriction?

My scenario was AutoML NLP for Entity Extraction. It seems to support JSONL for Entity Analysis while the other methods don't. per [](https://cloud.google.com/natural-language/automl/docs/predict#batch_prediction)

**Comment by munkhuushmgl** [comment] 2020-05-07 22:22
@hensilva @aaronbriel @tc64 I have tracked down the issue. Looks like there was a change that has not been updated on the documentation page. For NL entity extraction model with prefix `TEN****` your-model-id, it only supports `.jsonl`

For NL text classification model with prefix `TCN***YOUR-MODEL-ID`, it only supports `test.csv` file; sample rows: 
```
gs://your-bucket/some-text-file.txt
gs://your-bucket/some-pdf-file.pdf
gs://your-bucket/second-text-file.txt
```

I was able to reproduce your error passing `.csv` file that contains 
```
first example text
second example text
third example text
```

Our documentation will be updated on the next release.

With this note, I am closing this issue.

**Closed by munkhuushmgl** 2020-05-07 22:22 UTC
Labels: :rotating_light:, api: automl, triage me

**Comment by aaronbriel** [comment] 2020-05-07 22:34
@munkhuushmgl So this confirms that BatchPredict only works for entity extraction and not text classification, as jsonl is not a supported file type in the latter.

**Comment by munkhuushmgl** [comment] 2020-05-07 22:57
@aaronbriel BatchPredict works Text Classification only if you provide `.csv` file with sample rows 
```
gs://your-bucket/some-text-file.txt
gs://your-bucket/some-pdf-file.pdf
gs://your-bucket/second-text-file.txt
```

**Comment by munkhuushmgl** [comment] 2020-05-07 23:04
@aaronbriel I have tested on my local machine

my setup

OS: macOS
python: 3.6
same api versions as the above

Here is the code I have used:

```
def batch_predict(project_id, model_id, input_uri, output_uri):
    """Batch predict"""
    # [START automl_batch_predict]
    from google.cloud import automl

    # TODO(developer): Uncomment and set the following variables
    # project_id = "YOUR_PROJECT_ID"
    # model_id = "YOUR_MODEL_ID"
    # input_uri = "gs://YOUR_BUCKET_ID/path/to/your/input/csv_or_jsonl"
    # output_uri = "gs://YOUR_BUCKET_ID/path/to/save/results/"

    prediction_client = automl.PredictionServiceClient()

    # Get the full path of the model.
    model_full_id = prediction_client.model_path(project_id, "us-central1", model_id)

    gcs_source = automl.types.GcsSource(input_uris=[input_uri])

    input_config = automl.types.BatchPredictInputConfig(gcs_source=gcs_source)
    gcs_destination = automl.types.GcsDestination(output_uri_prefix=output_uri)
    output_config = automl.types.BatchPredictOutputConfig(
        gcs_destination=gcs_destination
    )

    response = prediction_client.batch_predict(
        model_full_id, input_config, output_config
    )

    print("Waiting for operation to complete...")
    print(
        "Batch Prediction results saved to Cloud Storage bucket. {}".format(
            response.result()
        )
    )
    # [END automl_batch_predict]


batch_predict(
    "YOUR-GCP-PROJECT",
    "TCN******************", # your text classification model ID
    "gs://bucket/test-2.csv",
    "gs://bucket/output_uri/",
)
```

**Comment by aaronbriel** [comment] 2020-05-08 17:52
@munkhuushmgl I'm aware of the functionality you describe. I believe the desired solution is to be able to process a csv or jsonl that contains multiple rows of text instead of rows that point to individual files each containing the text to process, as the latter is extremely inefficient.

**Comment by munkhuushmgl** [comment] 2020-05-08 20:16
@aaronbriel I found out the reasoning behind not support the feature u described is that it will cause ambiguity on which lines belong to the same text/document. I will definitely emphasize this feature on the next release.

**Comment by aaronbriel** [comment] 2020-05-08 20:36
Thanks @munkhuushmgl!!

**Comment by daehwan7** [comment] 2020-05-25 07:03
@munkhuushmgl  hi, I adapted for batch prediction as your suggestion. so I created files list of predict, .csv file that contains these samples

> gs://your-bucket/some-text-file1.txt
> gs://your-bucket/some-pdf-file2.txt

but I discovered another problem below:
`
---------------------------------------------------------------------------
GoogleAPICallError                        Traceback (most recent call last)
<ipython-input-280-1697b55b23c1> in <module>()
     31 print(
     32     "Batch Prediction results saved to Cloud Storage bucket. {}".format(
---> 33         response.result()
     34     )
     35 )

/usr/local/lib/python3.5/dist-packages/google/api_core/future/polling.py in result(self, timeout)
    125             # pylint: disable=raising-bad-type
    126             # Pylint doesn't recognize that this is valid in this case.
--> 127             raise self._exception
    128 
    129         return self._result
GoogleAPICallError: None INTERNAL
---------------------------------------------------------------------------
`
I really don't know what the problem is.....
AutoML Natural language is not stable yet ?

**Comment by munkhuushmgl** [comment] 2020-05-28 18:56
Hello Daehwan

I will need more context from your end. (provide your steps to produce this
error)
I have just tested again on my local machine, and it looks like everything
works fine.
[image: image.png]

Steps produce this output:

   1.

   pip install virtualenvvirtualenv <your-env>source
<your-env>/bin/activate<your-env>/bin/pip install google-cloud-automl

   2.

   Python version 3.6 or 3.7 --> python3.6 batch_predict.py

   3.

   code snippet:


   def batch_predict(project_id, model_id, input_uri, output_uri):
   """Batch predict"""
   # [START automl_batch_predict]
   from google.cloud import automl

   # TODO(developer): Uncomment and set the following variables
   # project_id = "YOUR_PROJECT_ID"
   # model_id = "YOUR_MODEL_ID"
   # input_uri = "gs://YOUR_BUCKET_ID/path/to/your/input/csv_or_jsonl"
   # output_uri = "gs://YOUR_BUCKET_ID/path/to/save/results/"

   prediction_client = automl.PredictionServiceClient()

   # Get the full path of the model.
   model_full_id = prediction_client.model_path(
   project_id, "us-central1", model_id)

   gcs_source = automl.types.GcsSource(input_uris=[input_uri])

   input_config = automl.types.BatchPredictInputConfig(gcs_source
   =gcs_source)
   gcs_destination = automl.types.GcsDestination(output_uri_prefix
   =output_uri)
   output_config = automl.types.BatchPredictOutputConfig(
   gcs_destination=gcs_destination
   )

   response = prediction_client.batch_predict(
   model_full_id, input_config, output_config
   )

   print("Waiting for operation to complete...")
   print(
   "Batch Prediction results saved to Cloud Storage bucket. {}".format(
   response.result()
   )
   )
   # [END automl_batch_predict]


   batch_predict(
   "your-google-project-id",
   "TCN00000000000000", # AutoML NL text classifciation model
   "gs://your-gcs-bucket/test.csv",
   "gs://your-gcs-bucket/output_uri/",
   )

**Comment by tc64** [comment] 2020-07-26 17:33
> @hensilva @aaronbriel @tc64 I have tracked down the issue. Looks like there was a change that has not been updated on the documentation page. For NL entity extraction model with prefix `TEN****` your-model-id, it only supports `.jsonl`
> 
> For NL text classification model with prefix `TCN***YOUR-MODEL-ID`, it only supports `test.csv` file that contains sample rows:
> 
> ```
> gs://your-bucket/some-text-file.txt
> gs://your-bucket/some-pdf-file.pdf
> gs://your-bucket/second-text-file.txt
> ```
> 
> I was able to reproduce your error passing `.csv` file that contains
> 
> ```
> first example text
> second example text
> third example text
> ```
> 
> Our documentation will be updated on the next release.
> 
> With this note, I am closing this issue.

@munkhuushmgl sorry for not replying sooner, thanks for figuring it out. I'm a bit disappointed since this makes short text classification less efficient (I now have to create a separate file for each short text). Do you know if there is any plan to allow passing a single file with many short texts (one per line) for this kind of use case?

**Comment by Klevmarken** [comment] 2020-09-10 11:37
@munkhuushmgl @tc64  I would very much like to know if there is a solution like this available soon as well? 

`@munkhuushmgl sorry for not replying sooner, thanks for figuring it out. I'm a bit disappointed since this makes short text classification less efficient (I now have to create a separate file for each short text). Do you know if there is any plan to allow passing a single file with many short texts (one per line) for this kind of use case?`

Right now if one would like to analyze thousands of one liner texts this would entail either making thousands of  API requests or thousands of files stored on gcs. Either way is really inefficient. Best solution would be to upload a single CSV with all the texts (one on each row) and then have it analyzed and the results saved under the output_uri.

**Comment by nayan-mehta** [comment] 2021-09-13 21:05
> @aaronbriel BatchPredict works for Text Classification only if you provide `.csv` file with sample rows
> 
> ```
> gs://your-bucket/some-text-file.txt
> gs://your-bucket/some-pdf-file.pdf
> gs://your-bucket/second-text-file.txt
> ```

The docs for classification definitely are confusing, you would think that the paths are separated by commas, that's the mistake that I made.

**Comment by Tum86** [comment] 2021-12-31 11:37
Hello,
I still have the problem. 
I have created a corresponding csv file in which every single line refers to a PDF in my bucket (see attachment). Nevertheless I get the error message "InvalidArgument: 400 BatchPredict could not start due to empty input CSV file"
[data_test_pdf_dataset.csv](https://github.com/googleapis/python-automl/files/7796072/data_test_pdf_dataset.csv)

I would be infinitely grateful for help in this case....
